---
output: md_document
---

### Crear un marco de datos en R

Primero creamos los vectores

```{r}
apellidos <- rep(c('García','Rodríguez','Pérez','García','González'),4)

nombres <- rep(c('Juan','Pedro','Juana','María','Marta'),4)

sexos <- rep(c('M','M','F','X','F'),4)

edades <- c(21:40)

nacionalidades <- rep(c('arg','arg','chi','bol','arg'),4)

dias <- c(1:10,21:30)

meses <- c('5','4','3','2','1','11','12','2','1','4','6','8','10','12','11','9','7','5','3','1')

anios <- c(1981:2000)

```

Luego creamos el marco de datos

```{r}
df <- data.frame(apellido = apellidos,
                 nombre = nombres,
                 sexo = sexos,
                 edad = edades,
                 nacionalidad = nacionalidades,
                 dia = dias,
                 mes = meses,
                 anio = anios)
head(df)
```

Ahora inspeccionamos qué tipo de datos contiene

```{r}
str(df)
```

###### Corra el código en Google Colab desde este [link](https://colab.research.google.com/drive/1OJUobzElX-QJ2ty_UQDrbWHW4T4c1oe5?usp=sharing "Google Colab").
